name: py311-osx-aws
channels:
  - apple
dependencies:
  - python=3.11.9
  - pip
  - pip:
    - boto3>=1.28.38
    - aws_lambda_typing>=2.20.0
    - duckdb>=0.10.1
    - pandas>=2.1.4
    - aiohttp>=3.10.2
    # dev tools
    - ruff>=0.0.271
    - yapf>=0.33.0
    - ipython
    - jedi-language-server
