name: Docker Build and Push (read-earthquake)

on:
  push:
    branches:
      - master
    paths:
      - 'read-earthquake/**'
  pull_request:
    branches:
      - master
    paths:
      - 'read-earthquake/**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
      ECR_REPO: ${{ secrets.AWS_ECR_REPO_PROCESSEQ }}
      IMAGE_TAG: latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: ${{ secrets.AWS_REGION }}
          registry-type: private

      - name: Build, tag, and push Docker image to Amazon ECR
        run: |
          # Build the Docker image
          docker build -t $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG \
            -f read-earthquake/Dockerfile read-earthquake
          docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG

      - name: Logout from Amazon ECR
        run: docker logout $ECR_REGISTRY
